CREATE TABLE sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    stock_symbol TEXT NOT NULL,
    stock_price NUMERIC NOT NULL,
    shares INTEGER NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);